FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libusb-1.0-0-dev libbfd-dev libelf-dev libftdi1-dev git libiberty-dev build-essential

COPY . /repo
WORKDIR /repo
RUN make get_version
RUN make 

FROM ubuntu:20.04 as package
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libbfd-dev
COPY --from=builder /repo/ofiles/orbstat /